### ISSUE TITLE
Crash in optimization after some iterations

### ISSUE THREAD

**Issue by SouthEndMusic** [mitsuba-renderer/drjit#117]
Hi,

I'm running a PyTorch geometry optimization pipeline including Mitsuba with `wrap_ad`. The optimization runs fine for 144 iterations, but then the Python kernel crashes with the following error:

`Critical Dr.Jit compiler failure: jit_optix_compile(): optixModuleGetCompilationState() indicates that the compilation did not complete succesfully. The module's compilation state is: 0x2363`.

I could provide a minimal example if requested, but hopefully the problem can be resolved without.

Here's some system information:
- OS: Windows 10
- GPU: NVIDIA GeForce RTX 3090 (driver: 527.56)
- Python: 3.9.13
- Dr.jit: 0.3.2
- Mitsuba: 3.1.1
- PyTorch: 1.13.1

Thanks in advance!

**Comment by njroussel** [comment]
Hi @SouthEndMusic 

This might have been fixed in https://github.com/mitsuba-renderer/drjit-core/pull/44, as it seems similar to: https://github.com/mitsuba-renderer/mitsuba3/issues/408.
This hasn't be pushed into a public release yet, but should be available in the next release (later today hopefully).

**Comment by njroussel** [comment]
The new version is out, please tell us if it fixes the issue :pray:

**Comment by SouthEndMusic** [comment]
It works now with `drjit==0.4.0` and `mitsuba == 3.2.0`, thanks!
