### ISSUE TITLE
`dr.power(mi.Float(-1), mi.Int(3))` results in `[nan]`

### ISSUE THREAD

**Issue by maxfrei750** [mitsuba-renderer/drjit#140]
Why is that? Is it a bug, or has it something to do with the utilized data types?

Motivation: I'd like to produce alternating signs.

Thanks!

EDIT: This was using the `cuda_ad_rgb` backend. Using the `llvm_ad_rgb` backend, I receive

```
>>> dr.power(mi.Float(-1),mi.Int(3))
[2.535301200456459e+30]
```

With `scalar_rgb`, I receive
```
>>> dr.power(mi.Float(-1),mi.Int(3))
-1.0
```

**Comment by maxfrei750** [comment]
> Motivation: I'd like to produce alternating signs.

For that specific use-case, one can use 

```
>>> dr.cos(dr.arange(mi.Int, 0, 10) * dr.pi)
[1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, -1.0]
```

as a workaround, for now.

**Comment by maxfrei750** [comment]
Thanks for the elaboration and the more performant implementation of the alternating signs. So, if I understand you correctly, this means that the encountered behavior is expected, in which case it would be nice to have something like a hint in the documentation, so that other users are aware of the problem. Can you point me to the file, where the function is documented, so that I can add the hint? I couldn't find it ad-hoc, since the docs are generated automatically. Thanks!

**Comment by njroussel** [comment]
Hi @maxfrei750 

I never noticed this myself, but yes it seems like we only support strictly positive bases :exploding_head: .

The function is documented here: https://github.com/mitsuba-renderer/drjit/blob/master/drjit/router.py#L2857-L2881

**Comment by wjakob** [comment]
Complete implementations of `std::pow` including the special case for integer exponents that happen to be specified as floating point values are really long and complex. The decision to not support this case is intentional, since it would produce a large amount of branchy code in the JIT compiler.

That said,  we do handle scalar Python integer exponents specially. Does it work if you write `3` instead of `mi.Int(3)`?
