### ISSUE TITLE
Critical Dr.Jit compiler failure: cuda_check(): API error 0002 (CUDA_ERROR_OUT_OF_MEMORY)

### ISSUE THREAD

**Issue by owaranainatsu** [mitsuba-renderer/drjit#148]
Here is the error message when import drjit:

> Critical Dr.Jit compiler failure: cuda_check(): API error 0002 (CUDA_ERROR_OUT_OF_MEMORY): "out of memory" in /project/ext/drjit-core/src/cuda_core.cpp:171.
Aborted (core dumped)

However, I think there is still enough memory.
<img width="576" alt="image" src="https://github.com/mitsuba-renderer/drjit/assets/57721325/e01e91f2-d40b-4d55-b9ca-92411e5db455">

**Comment by njroussel** [comment]
Hi @owaranainatsu 

This is surprising, the error is happening during the setup of the CUDA backend. Could you try "hiding" one GPU from Dr.Jit by using the `CUDA_VISIBLE_DEVICES` environment variable?

This section of the code that hasn't changed in quite some time - definitely not recently. You mentioned in #147 that you could previously use DrJit without this issue. I therefore believe that this issue is tied to something in your environment/setup/configuration rather than Dr.Jit itself.

**Comment by owaranainatsu** [comment]
Thank you for you reply!
I modified my code like this:
``` 
import os 
os.environ['CUDA_VISIBLE_DEVICES'] = '1'
import drjit as dr
```

Then I got error message like:

> jit_kernel_load(): cache file "/home/arrow/.drjit/f3b2e15858262a99b8b532d3ba2724a2.cuda.bin" is from an incompatible version of Dr.Jit. You may want to wipe your ~/.drjit directory.
jit_kernel_load(): cache file "/home/arrow/.drjit/f3b2e15858262a99b8b532d3ba2724a2.cuda.bin" is from an incompatible version of Dr.Jit. You may want to wipe your ~/.drjit directory.
jit_kernel_write(): could not link cache file "/home/arrow/.drjit/f3b2e15858262a99b8b532d3ba2724a2.cuda.bin" into file system: File exists
jit_kernel_write(): could not link cache file "/home/arrow/.drjit/f3b2e15858262a99b8b532d3ba2724a2.cuda.bin" into file system: File exists

**Comment by njroussel** [comment]
These are not error messages, just additional information. As indicated, you should delete your  `~/.drjit` directory.

**Comment by owaranainatsu** [comment]
Thank you very much!
