### ISSUE TITLE
Implement Gaussian Kernel on Image

### ISSUE THREAD

**Issue by LI-explorer** [mitsuba-renderer/drjit#240]
Hi,

I'm wondering if there's a way to implement the Gaussian kernel for convolution on images using the current version of DrJit. While using a for loop is a straightforward approach, it can potentially hinder the backward process. 

Do you have any suggestions or alternatives to efficiently integrate Gaussian kernel convolution without impacting the backward pass? Thanks.

**Comment by njroussel** [comment]
Hi @LI-explorer 

I'm not sure I understand what the issue is. Do you mind sharing some code? 
I think it's perfectly acceptable to use a normal python loop here, unless the kernel is unusually large. The number of iterations of the loop is static and known beforehand. You should have no issues backpropagating when using a normal python loop.
