### ISSUE TITLE
Custom Build on Windows drjit version troubles

### ISSUE THREAD

**Issue by DanielPSchenk** [mitsuba-renderer/drjit#266]
When building on Windows I ran into an error caused by drjit Version 0.4.2 not being available on PyPi. Apparently, the Version number from ext/drjit/include/drjit/fwd.h line 64-66 [in drjit repository on 23rd of August](https://github.com/mitsuba-renderer/drjit/blob/6e44e23224e97f30682dfe2428fe89c6c7b1953c/include/drjit/fwd.h#L64) is used to determine what version is required, and the main branch of the drjit repository is currently at 0.4.2
It was downgraded with [this commit](https://github.com/mitsuba-renderer/drjit/commit/cc75a14c65ee5d4719d2e7c0c0af297cdfdad302) two months ago

I was able to mitigate this issue by manually checking out the stable branch in the drjit submodule.
To permanently fix this, I would propose adding a line 
`branch = stable`
to .gitmodules.txt ensuring that a working version is used. This issue also breaks the release version 3.5.2 for me, which I can not build without manually checking out the drjit stable branch.

Build procedure:
just typing `pip install .` in repository root folder. With the release, it works on Windows after checking out drjit stable.
Compiler:
Microsoft Visual Studio 2019

**Comment by njroussel** [comment]
Hi @DanielPSchenk 

I'm a bit confused, because you never said it explicitly, you're building Mitsuba 3, correct?

>  the release version 3.5.2 for me, which I can not build without manually checking out the drjit stable branch.

The submodule `ext/drjit` submodule on `mitsuba3:v3.5.2` is pointing to  https://github.com/mitsuba-renderer/drjit/commit/4b022cb70d17367adddfdc6be10e0dd4e615d127 which is `drjit:stable`. Did you forget to update the submodules when checking out the `v3.5.2` tag?

Could you please provide us with an exact list of steps/commands that you're performing (from `git clone` to `pip install` and all the modifications in-between) so we better understand the issue? :smile:

**Comment by DanielPSchenk** [comment]
Hi @njroussel,
yes, I am building Mitsuba. 

To build from the release I 
1. downloaded the zip file
2. installed all the submodules from .gitmodules There is no mention of a specific commit. From .gitmodules
`[submodule "ext/drjit"]
	path = ext/drjit
	url = https://github.com/mitsuba-renderer/drjit`
3. `pip install .` Without checking out the stable branch manually, I run into the error

To build from main branch
1. git clone --recursive https://github.com/mitsuba-renderer/mitsuba3
2. `pip install .`
3. Run into error because the build system requires drjit 0.4.2 the submodule it initialized was at the main branch
