### ISSUE TITLE
Compile error with libstdc++ 11

### ISSUE THREAD

**Issue by Novum** [mitsuba-renderer/drjit#45]
https://github.com/mitsuba-renderer/drjit/blob/ab1bc8683049a8aadc8cc0233a26fb2ee14064bc/include/drjit/packet_intrin.h#L48

GCC 11 complains with:
`error: #error "Never use <bmi2intrin.h> directly; include <x86gprintrin.h> instead."`

**Comment by dvicini** [comment]
Hi,
We currently test only GCC 9 on the CI, so I am not surprised that GCC 11 would run into some minor issues here and there. Feel free to make a pull request with a fix. Otherwise, you could also just use Clang. We ran into issues with GCC every now and then, so pretty much everybody working on Dr.Jit and Mitsuba 3 is mostly using Clang.

**Comment by tomix1024** [comment]
I think I fixed this problem in #55 .
