### ISSUE TITLE
`ModuleNotFoundError: No module named 'drjit.drjit_ext'` when compiling `drjit` myself

### ISSUE THREAD

**Issue by maxfrei750** [mitsuba-renderer/drjit#67]
When I compile `drjit` myself using

```
git clone --recursive https://github.com/mitsuba-renderer/drjit
cd drjit
pip install .
```

I get the following error, when I try to import `drjit`:
```
>>> import drjit
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/workspace/drjit/drjit/__init__.py", line 24, in <module>
    import drjit.drjit_ext as drjit_ext  # noqa
ModuleNotFoundError: No module named 'drjit.drjit_ext'
```

Am I missing a dependency or a flag?

**Comment by maxfrei750** [comment]
In the meantime, I found additional information on how to compile in the `mitsuba3` repo: https://mitsuba.readthedocs.io/en/latest/src/developer_guide/compiling.html

Also, based on one of the [automated build logs ](https://rgl-ci.epfl.ch/viewLog.html?buildId=8548&buildTypeId=DrJitLinuxClang&tab=buildLog&branch_DrJit=%3Cdefault%3E&_focus=159#_state=159), I guess that I was maybe missing `libnvoptix.so.*` and `libnvidia-rtcore.so.*`.

I'll try again and let you know if I made any progress.

**Comment by maxfrei750** [comment]
@njroussel I have a follow-up question: I understand that `libnvoptix.so.*` and `libnvidia-rtcore.so.*` are specific to a certain driver, correct? If so, then how do you prepare the builds (e.g. on pypi) that run independently of the specific GPU driver?

**Comment by njroussel** [comment]
Hi @maxfrei750 !

The missing module error you are seeing is caused by Python's module search priority.
Before checking for installed packages, it will first look at the current working directory. So, if you're in the `where/you/cloned/drjit` folder, when you try to `import drjit` it will load the `__init__.py` in `where/you/cloned/drjit/drjit/__init__.py` instead of `.../site_packages/drjit/__init__.py`.

I was able to reproduce your error by doing the following:
```
git clone --recursive https://github.com/mitsuba-renderer/drjit
cd drjit
pip install .
python -c "import drjit"
```
So make sure you're not in folder where you cloned `drjit` before you try using it :smiley: 

--------

As for the Nvidia shared libraries, they are dynamically loaded at runtime from the host's machine. They are not included in the Python package. If you're curious about how this works, take a look at [this function](https://github.com/mitsuba-renderer/drjit-core/blob/1834d2bb3599130c085815f50ac7a688f021ed33/src/init.cpp#L595). The same is done to find/load/use LLVM [here](https://github.com/mitsuba-renderer/drjit-core/blob/master/src/llvm_api.cpp#L544-L567).

What you're seeing in the build logs is specific to our CI machine, we're running the builds and tests inside of Docker container where these shared libraries are (initially) missing. So we need to copy them over from the host.

**Comment by maxfrei750** [comment]
> The missing module error you are seeing is caused by Python's module search priority.

![image](https://c.tenor.com/Oaq1HNMNDVsAAAAd/facepalm-crowd.gif)

Thank you so much. Now everything works as expected. :sweat_smile:
